(function(){
'use strict';
var script=document.currentScript;
var scriptUrl=script&&script.src?script.src:'';
var configUrl=scriptUrl?scriptUrl.replace(/cms-feed\.js(?:\?.*)?$/,'analytics-config.json'):'';
var isKh=document.documentElement.lang==='kha'||location.pathname.indexOf('/kh/')!==-1;
var lang=isKh?'kha':'en';
var apiBase='';

function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function formatDate(v){if(!v)return '';try{return new Date(v).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'});}catch(e){return v;}}
function loadConfig(){if(window.MERCY_API_BASE){apiBase=String(window.MERCY_API_BASE).replace(/\/$/,'');return Promise.resolve();}if(!configUrl)return Promise.reject(new Error('config_missing'));return fetch(configUrl,{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('config_failed');return r.json();}).then(function(c){apiBase=String(c.mercy_api_base||'').replace(/\/$/,'');if(!apiBase)throw new Error('api_missing');});}
function getJson(path){return fetch(apiBase+path,{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('request_failed');return r.json();});}
function currentPagesPrefix(){if(location.pathname.indexOf('/kh/pages/')!==-1||location.pathname.indexOf('/pages/')!==-1)return '';if(isKh)return 'pages/';return 'pages/';}
function postHref(slug){return currentPagesPrefix()+'post.html?slug='+encodeURIComponent(slug);}
function contentHref(slug){return currentPagesPrefix()+'content.html?slug='+encodeURIComponent(slug);}
function card(item){var a=document.createElement('article');a.className='cms-post-card'+(item.featured?' cms-featured':'');var html='';if(item.cover_image_url)html+='<img src="'+esc(item.cover_image_url)+'" alt="'+esc(item.cover_image_alt||'')+'" loading="lazy">';html+='<div class="cms-card-body"><div class="cms-meta"><span class="cms-chip">'+esc(item.content_type.replace(/-/g,' '))+'</span><span>'+esc(formatDate(item.published_at))+'</span>'+(item.pinned?'<span>📌</span>':'')+'</div><h3>'+esc(item.title)+'</h3><p>'+esc(item.summary||'')+'</p><a class="cms-post-link" href="'+esc(postHref(item.slug))+'">'+(isKh?'Pule shuh shuh →':'Read more →')+'</a></div>';a.innerHTML=html;return a;}
function renderFeed(root,items,limit){root.innerHTML='';var grid=document.createElement('div');grid.className='cms-feed-grid';(items||[]).slice(0,limit||items.length).forEach(function(x){grid.appendChild(card(x));});if(!grid.children.length){root.innerHTML='<div class="cms-empty">'+(isKh?'Ym pat don publication.':'No publications yet.')+'</div>';return;}root.appendChild(grid);}
function renderPosts(){document.querySelectorAll('[data-cms-posts-feed],[data-cms-latest]').forEach(function(root){root.classList.add('cms-loading');var latest=root.hasAttribute('data-cms-latest');var limit=latest?Number(root.getAttribute('data-limit')||3):30;getJson('/api/content/posts?language='+lang+'&limit='+Math.max(limit,1)).then(function(d){root.classList.remove('cms-loading');renderFeed(root,d.items||[],limit);}).catch(function(){root.classList.remove('cms-loading');root.innerHTML='<div class="cms-empty cms-error">'+(isKh?'Ym lah ban load ia ki post mynta.':'Could not load posts right now.')+'</div>';});});}
function renderBlocks(root,blocks){root.innerHTML='';(blocks||[]).forEach(function(b){var el;if(b.type==='heading'){el=document.createElement(b.level===3?'h3':'h2');el.textContent=b.text||'';}else if(b.type==='paragraph'){el=document.createElement('p');el.textContent=b.text||'';}else if(b.type==='callout'){el=document.createElement('div');el.className='cms-block-callout';el.textContent=b.text||'';}else if(b.type==='scripture'){el=document.createElement('div');el.className='cms-block-scripture';var p=document.createElement('p');p.textContent=b.text||'';el.appendChild(p);if(b.reference){var s=document.createElement('strong');s.textContent=b.reference;el.appendChild(s);}}else if(b.type==='quote'){el=document.createElement('blockquote');el.className='cms-block-quote';var q=document.createElement('p');q.textContent=b.text||'';el.appendChild(q);if(b.citation){var c=document.createElement('cite');c.textContent=b.citation;el.appendChild(c);}}else if(b.type==='image'){el=document.createElement('figure');el.className='cms-block-image';var img=document.createElement('img');img.src=b.url||'';img.alt=b.alt||'';img.loading='lazy';el.appendChild(img);if(b.caption){var cap=document.createElement('figcaption');cap.textContent=b.caption;el.appendChild(cap);}}else if(b.type==='button'){el=document.createElement('p');var link=document.createElement('a');link.className='btn primary';link.textContent=b.label||'Open';link.href=b.href||'#';if(/^https?:/i.test(link.href)){link.target='_blank';link.rel='noopener';}el.appendChild(link);}else if(b.type==='gallery'){el=document.createElement('div');el.className='cms-gallery';(b.items||[]).forEach(function(it){var gi=document.createElement('img');gi.src=it.url||'';gi.alt=it.alt||'';gi.loading='lazy';el.appendChild(gi);});}if(el)root.appendChild(el);});}
function renderDetail(kind){var root=document.querySelector(kind==='page'?'[data-cms-page-detail]':'[data-cms-post-detail]');if(!root)return;var params=new URLSearchParams(location.search);var slug=params.get('slug');if(!slug){root.innerHTML='<div class="cms-empty cms-error">Missing content slug.</div>';return;}var path=kind==='page'?'/api/content/pages/':'/api/content/posts/';getJson(path+encodeURIComponent(slug)+'?language='+lang).then(function(item){document.title=item.title+' · Mercy – The Last Hope of Salvation';var meta=root.querySelector('[data-cms-meta]'),title=root.querySelector('[data-cms-title]'),summary=root.querySelector('[data-cms-summary]'),cover=root.querySelector('[data-cms-cover]'),body=root.querySelector('[data-cms-body]'),blockRoot=root.querySelector('[data-cms-blocks]');if(meta)meta.textContent=(item.content_type||'').replace(/-/g,' ')+' · '+formatDate(item.published_at);if(title)title.textContent=item.title;if(summary){summary.textContent=item.summary||'';summary.hidden=!item.summary;}if(cover){if(item.cover_image_url){cover.src=item.cover_image_url;cover.alt=item.cover_image_alt||'';cover.hidden=false;}else cover.hidden=true;}if(body){body.innerHTML=item.body||'';body.querySelectorAll('a[target="_blank"]').forEach(function(a){a.rel='noopener noreferrer';});}if(blockRoot)renderBlocks(blockRoot,item.blocks||[]);}).catch(function(){root.innerHTML='<div class="cms-empty cms-error">'+(isKh?'Ym shem ia kane ka content.':'This content could not be found.')+'</div>';});}

loadConfig().then(function(){renderPosts();renderDetail('post');renderDetail('page');}).catch(function(){document.querySelectorAll('[data-cms-posts-feed],[data-cms-latest]').forEach(function(root){root.innerHTML='<div class="cms-empty cms-error">CMS API is not configured.</div>';});});
})();
