(function(){
'use strict';
var script=document.currentScript,scriptUrl=script&&script.src?script.src:'';
var configUrl=scriptUrl?scriptUrl.replace(/logos\.js(?:\?.*)?$/,'analytics-config.json'):'';
var apiBase='',currentReference='John 1:1',currentTab='interlinear',selectedTheme='',catalog=null;
var statusEl=document.getElementById('logosStatus'),referenceInput=document.getElementById('logosReference'),parallelRoot=document.getElementById('logosParallel'),tabPanel=document.getElementById('logosTabPanel'),themesRoot=document.getElementById('logosThemes'),aiRoot=document.getElementById('logosAiResponse'),askBtn=document.getElementById('logosAskBtn'),selectedThemeEl=document.getElementById('logosSelectedTheme'),questionEl=document.getElementById('logosQuestion');

function el(tag,className,text){var node=document.createElement(tag);if(className)node.className=className;if(text!=null)node.textContent=String(text);return node;}
function clear(node){while(node&&node.firstChild)node.removeChild(node.firstChild);}
function setStatus(text,error){if(!statusEl)return;statusEl.textContent=text;statusEl.style.color=error?'#9a1729':'';}
function loadConfig(){if(window.MERCY_API_BASE){apiBase=String(window.MERCY_API_BASE).replace(/\/$/,'');return Promise.resolve();}if(!configUrl)return Promise.reject(new Error('config_missing'));return fetch(configUrl,{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('config_failed');return r.json();}).then(function(c){apiBase=String(c.mercy_api_base||'').replace(/\/$/,'');if(!apiBase)throw new Error('api_missing');});}
function getJson(path){return fetch(apiBase+path,{cache:'no-store'}).then(function(r){if(!r.ok)return r.json().catch(function(){return {};}).then(function(d){var e=new Error(d.detail||'request_failed');e.status=r.status;throw e;});return r.json();});}
function postJson(path,body){return fetch(apiBase+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'}).then(function(r){if(!r.ok)return r.json().catch(function(){return {};}).then(function(d){var e=new Error(d.detail||'request_failed');e.status=r.status;throw e;});return r.json();});}
function humanStatus(value){return String(value||'unknown').replace(/-/g,' ');}
function safeLink(url,label){var a=el('a','',label||url);if(/^https:\/\//i.test(url||'')){a.href=url;a.target='_blank';a.rel='noopener noreferrer';}return a;}

function renderParallel(data){clear(parallelRoot);document.getElementById('passageHeading').textContent=data.reference||currentReference;var order=['en','he','la','arc','grc'];order.forEach(function(code){var row=(data.languages||{})[code];if(!row)return;var card=el('article','logos-language-card');card.dataset.code=code;var h=el('h3','',row.label||code.toUpperCase());var pill=el('span','logos-status-pill '+((row.status==='pending'||row.status==='provisional')?row.status:''),humanStatus(row.status));h.appendChild(pill);card.appendChild(h);if(row.text){var p=el('p','',row.text);if(code==='he'||code==='arc')p.dir='rtl';card.appendChild(p);}else card.appendChild(el('p','',row.note||'This language lane is not available for this passage.'));if(row.source){card.appendChild(el('span','logos-source-badge',(row.source.title||row.source.id)+' · '+humanStatus(row.source.rights)));}if(row.note&&row.text)card.appendChild(el('small','',row.note));parallelRoot.appendChild(card);});if(!parallelRoot.children.length)parallelRoot.appendChild(el('div','logos-error','No language lanes are available.'));}

function renderInterlinear(data){clear(tabPanel);var intro=el('div','');intro.appendChild(el('h2','',data.label||'Interlinear'));intro.appendChild(el('p','logos-note',data.note||''));tabPanel.appendChild(intro);var wrap=el('div','logos-interlinear-wrap'),table=el('table','logos-interlinear'),thead=el('thead'),tr=el('tr');['Text','Transliteration','Lemma','Morphology','Gloss'].forEach(function(x){tr.appendChild(el('th','',x));});thead.appendChild(tr);table.appendChild(thead);var tbody=el('tbody');(data.tokens||[]).forEach(function(t){var r=el('tr');var td=el('td','logos-script-token',t.surface||'');if(data.language==='he'||data.language==='arc')td.dir='rtl';r.appendChild(td);r.appendChild(el('td','',t.transliteration||''));r.appendChild(el('td','',t.lemma||''));r.appendChild(el('td','',t.morphology||''));r.appendChild(el('td','',t.gloss||''));tbody.appendChild(r);});table.appendChild(tbody);wrap.appendChild(table);tabPanel.appendChild(wrap);if(!(data.tokens||[]).length)tabPanel.appendChild(el('div','logos-error','No interlinear tokens are installed for this passage yet.'));}

function renderCommentary(data){clear(tabPanel);tabPanel.appendChild(el('h2','','Exegetical commentary'));var grid=el('div','logos-commentary-grid');Object.keys(data.commentary||{}).forEach(function(key){var card=el('article','logos-study-card');card.appendChild(el('h3','',key.charAt(0).toUpperCase()+key.slice(1)));card.appendChild(el('p','',data.commentary[key]));grid.appendChild(card);});tabPanel.appendChild(grid);var j=el('div','logos-policy');j.appendChild(el('strong','','Jerome Biblical Commentary'));j.appendChild(el('p','',data.jerome_biblical_commentary&&data.jerome_biblical_commentary.reason||'Reference-only.'));tabPanel.appendChild(j);}

function renderFathers(data){clear(tabPanel);tabPanel.appendChild(el('h2','','Church Fathers & Catena Aurea'));var grid=el('div','logos-fathers-grid');(data.fathers||[]).forEach(function(row){var card=el('article','logos-study-card');card.appendChild(el('h3','',row.father||'Church Father'));card.appendChild(el('strong','',row.work||''));card.appendChild(el('p','',row.summary||''));card.appendChild(el('small','',humanStatus(row.source_status)));grid.appendChild(card);});(data.catena_aurea||[]).forEach(function(row){var card=el('article','logos-study-card');card.appendChild(el('h3','',row.father||'Catena Aurea'));card.appendChild(el('strong','',row.work||''));card.appendChild(el('p','',row.summary||''));card.appendChild(el('small','',row.source_id||''));grid.appendChild(card);});if(!grid.children.length)grid.appendChild(el('div','logos-error','No patristic entries are installed for this passage yet.'));tabPanel.appendChild(grid);tabPanel.appendChild(el('p','logos-note',data.rights_note||''));}

function renderPreacher(data){clear(tabPanel);tabPanel.appendChild(el('h2','','Catholic preacher’s outline'));var outline=data.outline||{},card=el('article','logos-study-card');card.appendChild(el('h3','',outline.title||data.reference||'Outline'));var ol=el('ol','logos-outline');(outline.movements||[]).forEach(function(x){ol.appendChild(el('li','',x));});card.appendChild(ol);if(outline.caution){var caution=el('div','logos-policy');caution.appendChild(el('strong','','Preaching caution'));caution.appendChild(el('p','',outline.caution));card.appendChild(caution);}tabPanel.appendChild(card);tabPanel.appendChild(el('p','logos-note',data.editorial_note||''));}

function mapUrl(lat,lon){var span=.035,bbox=[lon-span,lat-span,lon+span,lat+span].join(',');return 'https://www.openstreetmap.org/export/embed.html?bbox='+encodeURIComponent(bbox)+'&layer=mapnik&marker='+encodeURIComponent(lat+','+lon);}
function renderPlaces(data){clear(tabPanel);tabPanel.appendChild(el('h2','','Biblical history & archaeology'));var grid=el('div','logos-place-grid');(data.items||[]).forEach(function(place){var card=el('article','logos-study-card');card.appendChild(el('h3','',place.name));card.appendChild(el('p','',place.historical_note||''));var arch=el('p');arch.appendChild(el('strong','','Archaeology: '));arch.appendChild(document.createTextNode(place.archaeology_note||''));card.appendChild(arch);card.appendChild(el('small','',(place.references||[]).join(' · ')));var frame=el('iframe','logos-map');frame.loading='lazy';frame.referrerPolicy='no-referrer';frame.title='Map of '+place.name;frame.src=mapUrl(place.lat,place.lon);card.appendChild(frame);grid.appendChild(card);});tabPanel.appendChild(grid);tabPanel.appendChild(el('p','logos-note',data.method_note||''));}

function renderMedia(data){clear(tabPanel);tabPanel.appendChild(el('h2','','Maps & licensed media'));var grid=el('div','logos-media-grid');(data.items||[]).forEach(function(row){var card=el('article','logos-study-card logos-media-card');var img=el('img');img.src=row.image_url||'';img.alt=row.title||'';img.loading='lazy';card.appendChild(img);card.appendChild(el('h3','',row.title||'Media'));var meta=el('div','logos-media-meta');meta.appendChild(document.createTextNode((row.kind||'media')+' · '+(row.rights||'rights not recorded')+' · '+(row.credit||'')));meta.appendChild(document.createElement('br'));meta.appendChild(safeLink(row.source_url,'Open source & license record'));card.appendChild(meta);grid.appendChild(card);});if(!grid.children.length)grid.appendChild(el('div','logos-error','No media has passed the rights gate yet.'));tabPanel.appendChild(grid);tabPanel.appendChild(el('p','logos-note',data.rights_note||''));}

function renderSources(data){clear(tabPanel);tabPanel.appendChild(el('h2','','Source-rights registry'));var wrap=el('div','logos-interlinear-wrap'),table=el('table','logos-rights-table'),head=el('thead'),tr=el('tr');['Source','Language','Status','Rights','Allowed display'].forEach(function(x){tr.appendChild(el('th','',x));});head.appendChild(tr);table.appendChild(head);var body=el('tbody');(data.items||[]).forEach(function(row){var r=el('tr');r.appendChild(el('td','',row.title||row.id));r.appendChild(el('td','',row.language||''));r.appendChild(el('td','',humanStatus(row.status)));r.appendChild(el('td','',humanStatus(row.rights)));r.appendChild(el('td','',humanStatus(row.allowed_display_scope)));body.appendChild(r);});table.appendChild(body);wrap.appendChild(table);tabPanel.appendChild(wrap);var policy=el('div','logos-policy');policy.appendChild(el('strong','','Copyright and provenance rule'));policy.appendChild(el('p','',data.policy&&data.policy.rule||''));tabPanel.appendChild(policy);}

function loadTab(){tabPanel.innerHTML='<div class="logos-loading">Loading study layer…</div>';var path,render;if(currentTab==='interlinear'){path='/api/logos/interlinear?reference=';render=renderInterlinear;}else if(currentTab==='commentary'){path='/api/logos/commentary?reference=';render=renderCommentary;}else if(currentTab==='fathers'){path='/api/logos/fathers?reference=';render=renderFathers;}else if(currentTab==='preacher'){path='/api/logos/preacher?reference=';render=renderPreacher;}else if(currentTab==='places'){path='/api/logos/places?reference=';render=renderPlaces;}else if(currentTab==='media'){path='/api/logos/media?reference=';render=renderMedia;}else{path='/api/logos/source-rights?reference=';render=renderSources;}getJson(path+encodeURIComponent(currentReference)).then(render).catch(function(err){clear(tabPanel);tabPanel.appendChild(el('div','logos-error',err.message==='logos_passage_not_in_local_corpus'?'This reference is not yet in the local deterministic corpus. Magisterium AI can still study it below.':'Could not load this Logos layer right now.'));});}

function study(reference){reference=String(reference||'').trim();if(!reference)return;currentReference=reference;referenceInput.value=reference;setStatus('Loading '+reference+'…');getJson('/api/logos/passage?reference='+encodeURIComponent(reference)).then(function(data){renderParallel(data);currentReference=data.reference||reference;referenceInput.value=currentReference;setStatus('Live · '+currentReference);loadTab();}).catch(function(err){clear(parallelRoot);parallelRoot.appendChild(el('div','logos-error',err.message==='logos_passage_not_in_local_corpus'?'This passage is not yet in the local source-locked corpus. The full Bible import is intentionally blocked until each edition passes the source-rights gate. You can still use the Magisterium AI themes below for this reference.':'Could not load this passage.'));setStatus('Local corpus pending for '+reference,true);loadTab();});}

function renderThemes(items){clear(themesRoot);(items||[]).forEach(function(row){var b=el('button','',row.label);b.type='button';b.dataset.theme=row.id;b.addEventListener('click',function(){selectedTheme=row.id;themesRoot.querySelectorAll('button').forEach(function(x){x.classList.toggle('active',x===b);});askBtn.disabled=false;selectedThemeEl.textContent=row.label;});themesRoot.appendChild(b);});}
function renderAi(data){clear(aiRoot);var answer=el('div','answer',data.reply||'No response returned.');aiRoot.appendChild(answer);var sources=data.sources||[];if(sources.length){var section=el('div','sources');section.appendChild(el('strong','','Sources returned by Magisterium AI'));var ul=el('ul');sources.forEach(function(s){var li=el('li');if(s.url)li.appendChild(safeLink(s.url,s.title||s.authority||'Catholic source'));else li.appendChild(document.createTextNode(s.title||s.authority||'Catholic source'));if(s.reference)li.appendChild(document.createTextNode(' — '+s.reference));ul.appendChild(li);});section.appendChild(ul);aiRoot.appendChild(section);}}
function askAi(){if(!selectedTheme)return;askBtn.disabled=true;askBtn.textContent='Studying…';clear(aiRoot);aiRoot.appendChild(el('div','logos-loading','Asking Magisterium AI with the selected Logos theme…'));postJson('/api/logos/ai',{reference:currentReference,theme:selectedTheme,question:questionEl.value.trim(),language:'en'}).then(renderAi).catch(function(err){clear(aiRoot);var msg=err.message==='magisterium_not_configured'?'Magisterium AI is not configured on the backend.':err.status===429?'The AI request limit was reached. Please wait and try again.':'Magisterium AI could not answer this Logos request right now.';aiRoot.appendChild(el('div','logos-error',msg));}).finally(function(){askBtn.disabled=false;askBtn.textContent='Ask Magisterium AI';});}

function bind(){document.getElementById('logosReferenceForm').addEventListener('submit',function(e){e.preventDefault();study(referenceInput.value);});document.querySelectorAll('[data-reference]').forEach(function(b){b.addEventListener('click',function(){study(b.dataset.reference);});});document.querySelectorAll('[data-logos-tab]').forEach(function(b){b.addEventListener('click',function(){currentTab=b.dataset.logosTab;document.querySelectorAll('[data-logos-tab]').forEach(function(x){x.classList.toggle('active',x===b);});loadTab();});});document.getElementById('reloadLogos').addEventListener('click',function(){study(currentReference);});askBtn.addEventListener('click',askAi);document.addEventListener('mercy:live-refresh',function(){if(!document.hidden)study(currentReference);});}

bind();loadConfig().then(function(){return getJson('/api/logos/catalog');}).then(function(data){catalog=data;renderThemes(data.ai_themes||[]);setStatus('Logos API connected · '+data.book_count+'-book Catholic canon');study(currentReference);}).catch(function(){setStatus('Logos backend is not deployed yet. The page shell is ready; deploy Mercy API v2.9.0 to activate study data.',true);clear(parallelRoot);parallelRoot.appendChild(el('div','logos-error','Logos requires the updated Mercy Cloud Run backend.'));});
})();
