(()=>{
  const scriptUrl=document.currentScript?.src||'',body=document.body,theme=localStorage.getItem('mercy-theme');
  if(theme==='dark')body.classList.add('dark');
  document.querySelector('.theme-btn')?.addEventListener('click',()=>{body.classList.toggle('dark');localStorage.setItem('mercy-theme',body.classList.contains('dark')?'dark':'light')});
  const menu=document.querySelector('.menu-btn'),nav=document.querySelector('#main-nav');
  menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});
  const p=location.pathname,isKh=p.includes('/kh/'),name=(p.split('/').pop()||'index.html'),query=location.search||'';
  if(isKh&&nav){nav.querySelectorAll('a').forEach(a=>{try{const u=new URL(a.getAttribute('href')||'',location.href);if(u.origin===location.origin&&u.pathname.includes('/pages/')&&!u.pathname.includes('/kh/pages/')){const f=u.pathname.split('/').pop();a.href=(p.includes('/kh/pages/')?'':'pages/')+f}}catch(e){}})}
  const themeBtn=document.querySelector('.theme-btn');
  if(themeBtn){const lang=document.createElement('a');lang.className='theme-btn';lang.style.textDecoration='none';lang.textContent=isKh?'English':'Khasi';lang.setAttribute('aria-label',isKh?'Switch to English':'Switch to Khasi');lang.title=isKh?'Open the same page in English':'Open the same page in Khasi';if(isKh){lang.href=p.includes('/kh/pages/')?'../../pages/'+name+query:'../index.html'+query}else{lang.href=p.includes('/pages/')?'../kh/pages/'+name+query:'kh/index.html'+query}themeBtn.before(lang)}
  document.querySelectorAll('[data-year]').forEach(x=>x.textContent=new Date().getFullYear());

  const configPromise=(async()=>{
    const cfg={mercy_api_base:(window.MERCY_API_BASE||'').replace(/\/$/,''),cloudflare_web_analytics_token:window.CLOUDFLARE_WEB_ANALYTICS_TOKEN||''};
    if(!scriptUrl)return cfg;
    try{const r=await fetch(new URL('analytics-config.json',scriptUrl),{cache:'no-store'});if(r.ok){const j=await r.json();cfg.mercy_api_base=(j.mercy_api_base||cfg.mercy_api_base||'').replace(/\/$/,'');cfg.cloudflare_web_analytics_token=j.cloudflare_web_analytics_token||cfg.cloudflare_web_analytics_token||''}}catch(e){}
    if(cfg.cloudflare_web_analytics_token&&!document.querySelector('script[data-mercy-cloudflare]')){const s=document.createElement('script');s.type='module';s.defer=true;s.src='https://static.cloudflareinsights.com/beacon.min.js';s.dataset.mercyCloudflare='1';s.setAttribute('data-cf-beacon',JSON.stringify({token:cfg.cloudflare_web_analytics_token}));document.head.appendChild(s)}
    return cfg;
  })();

  const search=document.querySelector('[data-saint-search]');
  if(search){search.addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();document.querySelectorAll('[data-saint]').forEach(el=>el.hidden=q&&!el.dataset.saint.includes(q))})}
  document.querySelectorAll('.saint-list article.saint-item[id]').forEach(article=>{const href='saint.html?id='+encodeURIComponent(article.id),nameLink=article.querySelector('h3 a'),sourceLink=article.querySelector('.saint-source a');if(nameLink){nameLink.href=href;nameLink.removeAttribute('target');nameLink.removeAttribute('rel')}if(sourceLink){sourceLink.href=href;sourceLink.removeAttribute('target');sourceLink.removeAttribute('rel');sourceLink.textContent=isKh?'Plie ia ka profile →':'Open saint profile →'}});
  const miracleImages={"Church of San Francesco in Lanciano, Italy":"https://commons.wikimedia.org/wiki/Special:Redirect/file/San%20Francesco%2C%20Lanciano.JPG?width=900","Orvieto Cathedral, Italy":"https://commons.wikimedia.org/wiki/Special:Redirect/file/Orvieto%20DuomoFacade.jpg?width=900","Church associated with the Holy Miracle in Santarem, Portugal":"https://commons.wikimedia.org/wiki/Special:Redirect/file/Milagre%20Eucar%C3%ADstico%20de%20Santar%C3%A9m.png?width=900","Basilica of San Francesco in Siena, Italy":"https://commons.wikimedia.org/wiki/Special:Redirect/file/SanFrancescoSienaDaSudest1.JPG?width=900"};
  document.querySelectorAll('.card-image').forEach(img=>{if(miracleImages[img.alt])img.src=miracleImages[img.alt]});
  document.querySelectorAll('[data-copy]').forEach(btn=>btn.addEventListener('click',async()=>{const el=document.querySelector(btn.dataset.copy);if(!el)return;await navigator.clipboard.writeText(el.innerText);const old=btn.textContent;btn.textContent=isKh?'La copy':'Copied';setTimeout(()=>btn.textContent=old,1200)}));

  const form=document.querySelector('[data-prayer-form]');
  if(form){form.addEventListener('submit',async e=>{e.preventDefault();const status=form.querySelector('.status'),cfg=await configPromise,api=cfg.mercy_api_base;if(!api){status.textContent=isKh?'Ka frontend ka la live; ka secure submission kan treikam ynda la configure ia ka cloud API.':'The GitHub Pages frontend is live. Secure submission activates when the included cloud API is deployed and MERCY_API_BASE is configured.';return}const payload=Object.fromEntries(new FormData(form).entries());try{const r=await fetch(api+'/api/prayer-intentions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('Request failed');form.reset();status.textContent=isKh?'La pdiang ia ka prayer intention jong phi.':'Your prayer intention was received. It will be handled privately.'}catch(err){status.textContent=isKh?'Ka submission kam treikam mynta. Sngewbha pyrshang biang.':'Submission is unavailable right now. Please try again later.'}})}

  const campaign=document.querySelector('[data-save-one-soul-campaign]');
  if(campaign){
    const tokenKey='mercy-save-one-soul-token-v1',language=isKh?'kha':'en',statusEl=campaign.querySelector('[data-campaign-status]'),joinBtn=campaign.querySelector('[data-campaign-join]'),completeBtn=campaign.querySelector('[data-campaign-complete]'),dayBtns=[...campaign.querySelectorAll('[data-campaign-day]')],joinedCount=campaign.querySelector('[data-campaign-joined-count]'),completedCount=campaign.querySelector('[data-campaign-completed-count]');
    const msg=(en,kh)=>isKh?kh:en;
    const newToken=()=>crypto.randomUUID?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(24)),b=>b.toString(16).padStart(2,'0')).join('');
    const getToken=()=>localStorage.getItem(tokenKey)||'';
    const setStatus=t=>{if(statusEl)statusEl.textContent=t};
    const apiCall=async(path,options={})=>{const cfg=await configPromise;if(!cfg.mercy_api_base)throw new Error('api_not_configured');const r=await fetch(cfg.mercy_api_base+path,options);if(!r.ok){const err=new Error('api_error');err.status=r.status;throw err}return r.json()};
    const render=state=>{const joined=!!state?.joined,days=state?.days||Array(7).fill(false);if(joinBtn){joinBtn.disabled=joined;joinBtn.textContent=joined?msg('Mission joined','La rung sha ka mission'):msg('Join the 7-Day Mission','Rung sha ka 7-Sngi Mission')}dayBtns.forEach((b,i)=>{b.disabled=!joined||!!days[i];b.classList.toggle('primary',!!days[i]);if(days[i])b.textContent=msg(`Day ${i+1} ✓`,`Sngi ${i+1} ✓`) });if(completeBtn){completeBtn.disabled=!joined||days.some(x=>!x)||!!state?.completed;completeBtn.textContent=state?.completed?msg('Mission completed ✓','La pyndep ia ka mission ✓'):msg('I completed the 7 days','Nga la pyndep 7 sngi')}if(joined)setStatus(state.completed?msg('Thank you for completing the seven-day prayer journey.','Khublei ba phi la pyndep ia ka lynti jingduwai 7 sngi.'):msg(`${state.days_completed||0} of 7 days recorded on this device.`,`La buh jingkynmaw ${state.days_completed||0} na 7 sngi ha kane ka device.`))};
    const loadStats=async()=>{try{const s=await apiCall('/api/save-one-soul/stats');if(joinedCount)joinedCount.textContent=Number(s.joined||0).toLocaleString();if(completedCount)completedCount.textContent=Number(s.completed||0).toLocaleString()}catch(e){if(joinedCount)joinedCount.textContent='—';if(completedCount)completedCount.textContent='—'}};
    joinBtn?.addEventListener('click',async()=>{try{let token=getToken();if(!token){token=newToken();localStorage.setItem(tokenKey,token)}setStatus(msg('Joining anonymously…','Dang rung anonymously…'));const state=await apiCall('/api/save-one-soul/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,language})});render(state);loadStats()}catch(e){setStatus(e.message==='api_not_configured'?msg('Participation tracking is ready but the Mercy API has not yet been connected to the live site.','Ka participation tracking ka la ready hynrei ym pat connect ia ka Mercy API sha live site.'):msg('Could not save your progress right now.','Ym lah ban save ia ka progress mynta.'))}});
    dayBtns.forEach(btn=>btn.addEventListener('click',async()=>{const token=getToken();if(!token)return;const day=Number(btn.dataset.campaignDay);try{const state=await apiCall('/api/save-one-soul/day',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,language,day})});render(state);loadStats()}catch(e){setStatus(msg('Could not record this day right now.','Ym lah ban buh jingkynmaw ia kane ka sngi mynta.'))}}));
    completeBtn?.addEventListener('click',async()=>{const token=getToken();if(!token)return;try{const state=await apiCall('/api/save-one-soul/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,language})});render(state);loadStats()}catch(e){setStatus(e.status===409?msg('Please mark all seven days first.','Sngewbha mark shwa ia baroh 7 sngi.'):msg('Could not complete the mission right now.','Ym lah ban pyndep ia ka mission mynta.'))}});
    (async()=>{await loadStats();const token=getToken();if(!token){render({joined:false});setStatus(msg('No personal data is requested. Your progress is tied only to a random token stored in this browser.','Ym kyrpad personal data. Ka progress ka shong tang ha random token ba la buh ha kane ka browser.'));return}try{const state=await apiCall('/api/save-one-soul/status/'+encodeURIComponent(token));render(state)}catch(e){render({joined:false})}})();
  }

  if('serviceWorker'in navigator&&scriptUrl){window.addEventListener('load',()=>navigator.serviceWorker.register(new URL('../mercy-sw.js',scriptUrl)).catch(()=>{}))}
})();
